### ISSUE TITLE
private message ;o)

### ISSUE THREAD

**Issue by Skamander** [killermenpl/thcTomcat#1]
Hi @killermenpl 

since github doesn't have private messages I thought I contact you here (since the repo seems to be empty). Hope that is ok.

You may want to incorporate the changes I made to the play cartridge. The old version didn't follow openshifts directory layout which can lead to problems (a newer deployed versions will be ignored and the older version will still be used). This is now fixed. The new layout should also allow for autoscaling.

btw: I'm curious, since the cartridge is relatively new and I didn't post links to it anywhere, how did you find the cartridge? If I use a search engine I only find it if I'm really specific about the repo name. :D

btw²: I saw that you created a windows.bat but it didn't work for deployment. Do you know why?

Cheers

**Comment by killermenpl** [comment]
I will merge from your repo in a few hours. To be honest, I don't really know juch about openshift. I just switched PostreSQL with MySQL. To find it I used Github's search and I searched for "Play2 Openshift" with sorting by Recently Updated. I don't know why the .bat doesn't work for you. Can you explain what you mean by deployment? Do you mean setting deployment to binary or deploying the .tgz? It is literary your .sh script with changed variables format to work with Windows. I will test it some more soon.

**Comment by Skamander** [comment]
Hi,

sorry, I didn't try the .bat file, I only read your comment in the deployment section of the readme and thought it doesn' work. It seems I misunderstand you: :D

```
Sadly, there is no way of doing this on Windows. I recommend installing any Linux distribution in virtual machine and using it only for that.
```
Hehe, I don't know much about openshift as well, only enough to run my sideprojects on it.

**Comment by killermenpl** [comment]
That line is about packaging into .tgz. It is impossible, since Windows doesn't have 'tar' command. I've got a workaround that I'm testing right now that *should* work, but it would require users to install additional software (7-zip).

**Comment by Skamander** [comment]
Oh, that would be great. If you get it working a pull request would be cool (or I could copy paste your code - whichever you like better).

**Comment by Skamander** [comment]
btw you have a typo in your create-scaled-play-app.sh. you forgot the "v" before v1.2 in the cartridge url.

https://github.com/killermenpl/openshift-scaled-play2-cartridge/blob/master/create-scaled-play-app.sh#L4
